version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/creditflow"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/creditflow"
    schedule:
      interval: "weekly"